config_vars: ./configs/config_vars.yaml

components_manager:
  components:

    jwt-middleware:
      secret-key: $j-secret-key

    server:
      listener:
        port: $server-port
        task_processor: main-task-processor
    secdist: {}
    default-secdist-provider:
      config: $secdist-path
    user-db:
      dbalias: user-db
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: true
      connlimit_mode: auto
      min_pool_size: 50
      max_pool_size: 1000
      max_queue_size: 10000 

    default-server-middleware-pipeline-builder:
      append:
        - jwt-middleware    

    profile-manager: {}
    profile-repository: {}
    s3-manager:
      access-key: $access-key
      secret-key: $secret-key


    testsuite-support: {}
    dns-client:
      fs-task-processor: fs-task-processor


    http-client:
      fs-task-processor: fs-task-processor

    update-avatar-handler:
      path: /profile/avatar
      method: PATCH
      max_request_size: 4194304
      task_processor: main-task-processor
    
    info-handler:
      path: /profile
      method: GET,POST
      task_processor: main-task-processor

    other-user-info-handler:
      path: /profile/{id}
      method: GET
      task_processor: main-task-processor
    
    logging:  
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stdout'
          level: $logger-level
          format: ltsv

  task_processors:
    main-task-processor:
      worker_threads: $worker-threads
    fs-task-processor:  
      worker_threads: $worker-fs-threads

  default_task_processor: main-task-processor