services:
  user_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdatabase
    hostname: user-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./AuthService/sql/init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    depends_on:
      user_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    hostname: auth-service
    ports:
      - 8080:8080


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'  
    ports:
      - 9092



    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --list --bootstrap-server localhost:9092"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
    
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
    - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    hostname: host-pgadmin  
    ports:
      - 5050:80
    depends_on:
      - user_db

volumes:
  postgres_data:
