config_vars: ./configs/config_vars.yaml

components_manager:
  components:

    jwt-middleware:
      secret-key: $j-secret-key

    server:
      listener:
        port: $server-port
        task_processor: main-task-processor
    
    chat-db:
      dbconnection: $db-path
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: true
      connlimit_mode: auto
      min_pool_size: 50
      max_pool_size: 1000
      max_queue_size: 10000 

    
    default-server-middleware-pipeline-builder:
      append:
        - jwt-middleware
  
    testsuite-support: {}

    dns-client:
            fs-task-processor: fs-task-processor

    create-conversation-handler:
      path: /chat/conversations
      method: POST
      task_processor: main-task-processor

    list-conversations-handler:
      path: /chat/conversations
      method: GET
      task_processor: main-task-processor

    send-message-handler:
      path: /chat/conversations/{conversation_id}/messages
      method: POST
      task_processor: main-task-processor

    get-messages-handler:
      path: /chat/conversations/{conversation_id}/messages
      method: GET
      task_processor: main-task-processor

    mark-as-read-handler:
      path: /chat/conversations/{conversation_id}/read
      method: POST
      task_processor: main-task-processor

    update-message-handler:
      path: /chat/messages/{message_id}
      method: PUT
      task_processor: main-task-processor

    delete-message-handler:
      path: /chat/messages/{message_id}
      method: DELETE
      task_processor: main-task-processor

    add-participant-handler:
      path: /chat/conversations/{conversation_id}/participants
      method: POST
      task_processor: main-task-processor

    remove-participant-handler:
      path: /chat/conversations/{conversation_id}/participants/{user_id_to_remove} # ИЗМЕНЕН ПУТЬ
      method: DELETE
      task_processor: main-task-processor
      
    leave-conversation-handler:
      path: /chat/conversations/{conversation_id}/leave
      method: DELETE
      task_processor: main-task-processor

    update-conversation-handler:
      path: /chat/conversations/{conversation_id}
      method: PUT
      task_processor: main-task-processor

    get-conversation-details-handler:
      path: /chat/conversations/{conversation_id}
      method: GET
      task_processor: main-task-processor
    


    logging:  
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stdout'
          level: $logger-level
          format: ltsv

  task_processors:
    main-task-processor:
      worker_threads: $worker-threads
    fs-task-processor:  
      worker_threads: $worker-fs-threads

  default_task_processor: main-task-processor

    


    

