config_vars: ./configs/config_vars.yaml

components_manager:
  components:
    server:
      listener:
        port: $server-port
        task_processor: main-task-processor
    secdist: {}
    default-secdist-provider:
      config: $secdist-path
    auth-db:
      dbalias: auth-db
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: true
      connlimit_mode: auto
      min_pool_size: 50
      max_pool_size: 1000
      max_queue_size: 10000    

    auth-manager: {}
    auth-repository: {}
    jwt-repository: {}
    producer: {}
    kafka-producer:
      delivery_timeout: 10s         
      queue_buffering_max: 100ms    
      enable_idempotence: true      
      security_protocol: PLAINTEXT
    
    jwt-manager:
      secret-key: $secret-key 
      access-token-lifetime: $access-token-lifetime
      refresh-token-lifetime: $refresh-token-lifetime
    

    testsuite-support: {}

    dns-client:
            fs-task-processor: fs-task-processor

    register-handler:
      path: /auth/register
      method: POST
      task_processor: main-task-processor
    login-handler:
      path: /auth/login
      method: POST
      task_processor: main-task-processor
    refresh-handler:
      path: /auth/refresh
      method: POST
      task_processor: main-task-processor
    logging:  
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stdout'
          level: $logger-level
          format: ltsv

  task_processors:
    main-task-processor:
      worker_threads: $worker-threads
    fs-task-processor:  
      worker_threads: $worker-fs-threads
    producer-task-processor:
      worker_threads: $producer-worker-threads
      thread_name: producer-worker

  default_task_processor: main-task-processor
