config_vars: ./configs/config_vars.yaml

components_manager:
  components:
    server:
      listener:
        port: $server-port
        task_processor: main-task-processor
    auth-db:
      dbconnection: $db-path 
      blocking_task_processor: fs-task-processor
      dns_resolver: async
      sync-start: true
      connlimit_mode: manual

    auth-manager: {}
    auth-repository: {}
    jwt-repository: {}
    
    jwt-manager:
      secret-key: $secret-key 
      access-token-lifetime: $access-token-lifetime
      refresh-token-lifetime: $refresh-token-lifetime
    

    testsuite-support: {}

    dns-client:
            fs-task-processor: fs-task-processor

    register-handler:
      path: /auth/register
      method: POST
      task_processor: main-task-processor
    login-handler:
      path: /auth/login
      method: POST
      task_processor: main-task-processor
    refresh-handler:
      path: /auth/refresh
      method: POST
      task_processor: main-task-processor
    logging:  
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stdout'
          level: $logger-level
          format: ltsv

  task_processors:
    main-task-processor:
      worker_threads: $worker-threads
    fs-task-processor:  
      worker_threads: $worker-fs-threads

  default_task_processor: main-task-processor